name: Build and Push Docker Image

on:
  push:
    branches:
      - deploy

jobs:
  start-do-runner:
    name: start self-hosted digitalocean runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-digitalocean-runner.outputs.label }}
      do-droplet-id: ${{ steps.start-digitalocean-runner.outputs.do-droplet-id }}
    steps:
      - name: start digitalocean runner
        id: start-digitalocean-runner
        uses: batpool/digitalocean-github-runner@v1.1
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          do-pat: ${{ secrets.DO_PERSONAL_ACCESS_TOKEN }}
          do-region: blr1
          do-image-id: ubuntu-22-10-x64
          do-droplet-type: s-1vcpu-2gb

  build-and-push:
    runs-on: ${{ needs.start-do-runner.outputs.label }}
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.gpu
          push: true
          tags: abiatop/wfs:${{ github.sha }}
          platforms: linux/amd64

  stop-do-runner:
    name: stop self-hosted digitalocean runner
    needs:
      - start-do-runner
      - do-the-job
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: stop digitalocean runner
        uses: batpool/digitalocean-github-runner@v1.1
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          do-pat: ${{ secrets.DO_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-do-runner.outputs.label }}
          do-droplet-id: ${{ needs.start-do-runner.outputs.do-droplet-id }}
