name: Build and Push Docker Image

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

     # Step 1.1: Cache the faster-whisper-large-v3 repository
      - name: Cache faster-whisper-large-v3 repository
        uses: actions/cache@v3
        with:
          path: faster-whisper-large-v3
          key: faster-whisper-large-v3

    # Step 1.2: Clone the systran/faster-whisper repository
      - name: Clone faster-whisper-large-v3 repository
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 https://huggingface.co/Systran/faster-whisper-large-v3 faster-whisper-large-v3
          rm -rf faster-whisper-large-v3/.git

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.gpu
          push: true
          tags: abiatop/wfs:${{ github.sha }}
          platforms: linux/amd64

